apiVersion: v1
kind: LimitRange
metadata:
  name: low-resource-range
spec:
  limits:
    - default:
        cpu: "2"
        memory: 2500Mi
      defaultRequest:
        cpu: "0.5"
        memory: 500Mi
      type: Container