apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql
    chart: mysql-1.6.2
    heritage: Helm
    release: mysql
  name: mysql
  selfLink: /api/v1/namespaces/default/services/mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer 
status:
  loadBalancer: {}
