apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: default
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    helm.sh/chart: kube-state-metrics-3.5.2
  name: prom-kube-state-metrics
  namespace: default
spec:
  clusterIP: 10.107.158.248
  clusterIPs:
  - 10.107.158.248
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31700
  selector:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/name: kube-state-metrics
