apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: default
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-14.11.0
    component: server
    heritage: Helm
    release: prom
  name: prom-prometheus-server
  namespace: default
spec:
  clusterIP: 10.99.205.105
  clusterIPs:
  - 10.99.205.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9090
    nodePort: 31500
  selector:
    app: prometheus
    component: server
    release: prom
